# Generated by Django 5.1 on 2024-08-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Марка')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('fuel_type', models.CharField(choices=[('бензин', 'бензин'), ('дизель', 'дизель'), ('электричество', 'электричество'), ('гибрид', 'гибрид')], max_length=40, verbose_name='Тип топлива')),
                ('transmission', models.CharField(choices=[('механическая', 'механическая'), ('автоматическая', 'автоматическая'), ('вариатор', 'вариатор'), ('робот', 'робот')], max_length=40, verbose_name='Тип КПП')),
                ('mileage', models.IntegerField(verbose_name='Пробег')),
                ('price', models.FloatField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Автомоболь',
                'verbose_name_plural': 'Автомоболи',
            },
        ),
    ]
